import { supabase, uidAsync } from '../lib/supabase';

export interface CreatePoolInput {
  title: string;
  question: string;
  options: string[];
  groupId?: string | null;
  closesAt?: Date;
}

/** Host creates a pool + its options; the share token is generated by the DB. */
export async function createPool(input: CreatePoolInput) {
  const host_id = await uidAsync();
  const { data: pool, error } = await supabase
    .from('pools')
    .insert({
      host_id,
      group_id: input.groupId ?? null,
      title: input.title,
      question: input.question,
      closes_at: input.closesAt?.toISOString() ?? null,
    })
    .select()
    .single();
  if (error) throw error;

  const rows = input.options
    .map((label, sort) => ({ pool_id: pool.id, label: label.trim(), sort }))
    .filter((o) => o.label.length > 0);
  const { error: optError } = await supabase.from('pool_options').insert(rows);
  if (optError) throw optError;

  return pool;
}

export async function getMyPools() {
  const { data, error } = await supabase
    .from('pools')
    .select('*, options:pool_options(id, label, sort), entries:pool_entries(id)')
    .order('created_at', { ascending: false })
    .limit(30);
  if (error) throw error;
  return data;
}

export async function getPool(poolId: string) {
  const { data, error } = await supabase
    .from('pools')
    .select('*, options:pool_options(id, label, sort), entries:pool_entries(id, display_name, option_id, created_at)')
    .eq('id', poolId)
    .single();
  if (error) throw error;
  return data;
}

/** Tally by option — same RPC the guest page uses. */
export async function getPoolResults(poolId: string) {
  const { data, error } = await supabase.rpc('pool_results', { p_pool: poolId });
  if (error) throw error;
  return (data ?? []) as { option_id: string; label: string; entries: number; pct: number }[];
}

export async function setPoolStatus(poolId: string, status: 'open' | 'locked' | 'settled') {
  const { error } = await supabase.from('pools').update({ status }).eq('id', poolId);
  if (error) throw error;
}

export async function settlePool(poolId: string, winningOptionId: string) {
  const { error } = await supabase
    .from('pools')
    .update({ status: 'settled', winning_option: winningOptionId })
    .eq('id', poolId);
  if (error) throw error;
}

/**
 * The URL guests open. Points at the `pool` edge function, which serves the
 * page itself — so there's no separate web host to deploy or pay for.
 */
export function poolShareUrl(shareToken: string): string {
  const base = process.env.EXPO_PUBLIC_SUPABASE_URL ?? '';
  return `${base}/functions/v1/pool/${encodeURIComponent(shareToken)}`;
}
